apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    project: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31523
  type: NodePort