apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9lZHUtZGV0ZXJtaW5lZC1qb2huc29uOjRNY1c4SGpLQDh0MElVUGVAcmMxYi1xaXR3a3cwa3dlZm5oYXN0Lm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9lZHUtZGV0ZXJtaW5lZC1qb2huc29uP3NzbG1vZGU9cmVxdWlyZQ==
  SECRET_KEY: aGtkdDQ1ODloamxkZXJ0ODk=
  ALLOWED_HOSTS: ZWR1LWRldGVybWluZWQtam9obnNvbi5zaXJpdXMtazhzLmR2bW4ub3Jn